// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: lagu.proto

package music

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lagu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Judul         string                 `protobuf:"bytes,2,opt,name=judul,proto3" json:"judul,omitempty"`
	AlbumId       int32                  `protobuf:"varint,3,opt,name=album_id,json=albumId,proto3" json:"album_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lagu) Reset() {
	*x = Lagu{}
	mi := &file_lagu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lagu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lagu) ProtoMessage() {}

func (x *Lagu) ProtoReflect() protoreflect.Message {
	mi := &file_lagu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lagu.ProtoReflect.Descriptor instead.
func (*Lagu) Descriptor() ([]byte, []int) {
	return file_lagu_proto_rawDescGZIP(), []int{0}
}

func (x *Lagu) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Lagu) GetJudul() string {
	if x != nil {
		return x.Judul
	}
	return ""
}

func (x *Lagu) GetAlbumId() int32 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

type GetLaguRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLaguRequest) Reset() {
	*x = GetLaguRequest{}
	mi := &file_lagu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLaguRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLaguRequest) ProtoMessage() {}

func (x *GetLaguRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lagu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLaguRequest.ProtoReflect.Descriptor instead.
func (*GetLaguRequest) Descriptor() ([]byte, []int) {
	return file_lagu_proto_rawDescGZIP(), []int{1}
}

func (x *GetLaguRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_lagu_proto protoreflect.FileDescriptor

const file_lagu_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"lagu.proto\x12\x05music\"G\n" +
	"\x04Lagu\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05judul\x18\x02 \x01(\tR\x05judul\x12\x19\n" +
	"\balbum_id\x18\x03 \x01(\x05R\aalbumId\" \n" +
	"\x0eGetLaguRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id2<\n" +
	"\vLaguService\x12-\n" +
	"\aGetLagu\x12\x15.music.GetLaguRequest\x1a\v.music.LaguB\x11Z\x0fmusic-api/musicb\x06proto3"

var (
	file_lagu_proto_rawDescOnce sync.Once
	file_lagu_proto_rawDescData []byte
)

func file_lagu_proto_rawDescGZIP() []byte {
	file_lagu_proto_rawDescOnce.Do(func() {
		file_lagu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lagu_proto_rawDesc), len(file_lagu_proto_rawDesc)))
	})
	return file_lagu_proto_rawDescData
}

var file_lagu_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lagu_proto_goTypes = []any{
	(*Lagu)(nil),           // 0: music.Lagu
	(*GetLaguRequest)(nil), // 1: music.GetLaguRequest
}
var file_lagu_proto_depIdxs = []int32{
	1, // 0: music.LaguService.GetLagu:input_type -> music.GetLaguRequest
	0, // 1: music.LaguService.GetLagu:output_type -> music.Lagu
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lagu_proto_init() }
func file_lagu_proto_init() {
	if File_lagu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lagu_proto_rawDesc), len(file_lagu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lagu_proto_goTypes,
		DependencyIndexes: file_lagu_proto_depIdxs,
		MessageInfos:      file_lagu_proto_msgTypes,
	}.Build()
	File_lagu_proto = out.File
	file_lagu_proto_goTypes = nil
	file_lagu_proto_depIdxs = nil
}
