// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: lagu.proto

package music

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LaguService_GetLagu_FullMethodName = "/music.LaguService/GetLagu"
)

// LaguServiceClient is the client API for LaguService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LaguServiceClient interface {
	GetLagu(ctx context.Context, in *GetLaguRequest, opts ...grpc.CallOption) (*Lagu, error)
}

type laguServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLaguServiceClient(cc grpc.ClientConnInterface) LaguServiceClient {
	return &laguServiceClient{cc}
}

func (c *laguServiceClient) GetLagu(ctx context.Context, in *GetLaguRequest, opts ...grpc.CallOption) (*Lagu, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Lagu)
	err := c.cc.Invoke(ctx, LaguService_GetLagu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LaguServiceServer is the server API for LaguService service.
// All implementations must embed UnimplementedLaguServiceServer
// for forward compatibility.
type LaguServiceServer interface {
	GetLagu(context.Context, *GetLaguRequest) (*Lagu, error)
	mustEmbedUnimplementedLaguServiceServer()
}

// UnimplementedLaguServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLaguServiceServer struct{}

func (UnimplementedLaguServiceServer) GetLagu(context.Context, *GetLaguRequest) (*Lagu, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLagu not implemented")
}
func (UnimplementedLaguServiceServer) mustEmbedUnimplementedLaguServiceServer() {}
func (UnimplementedLaguServiceServer) testEmbeddedByValue()                     {}

// UnsafeLaguServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LaguServiceServer will
// result in compilation errors.
type UnsafeLaguServiceServer interface {
	mustEmbedUnimplementedLaguServiceServer()
}

func RegisterLaguServiceServer(s grpc.ServiceRegistrar, srv LaguServiceServer) {
	// If the following call panics, it indicates UnimplementedLaguServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LaguService_ServiceDesc, srv)
}

func _LaguService_GetLagu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLaguRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaguServiceServer).GetLagu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LaguService_GetLagu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaguServiceServer).GetLagu(ctx, req.(*GetLaguRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LaguService_ServiceDesc is the grpc.ServiceDesc for LaguService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LaguService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "music.LaguService",
	HandlerType: (*LaguServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLagu",
			Handler:    _LaguService_GetLagu_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lagu.proto",
}
